-- MySQL Script generated by MySQL Workbench
-- 04/23/19 02:30:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warehouse` DEFAULT CHARACTER SET latin1 ;
USE `warehouse` ;

-- -----------------------------------------------------
-- Table `warehouse`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouse`.`category` ;

CREATE TABLE IF NOT EXISTS `warehouse`.`category` (
  `idCategory` INT(11) NOT NULL,
  `nameCategory` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `noDepartment` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `warehouse`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouse`.`customer` ;

CREATE TABLE IF NOT EXISTS `warehouse`.`customer` (
  `idCustomer` INT(11) NOT NULL,
  `nameCustomer` VARCHAR(45) NOT NULL,
  `phoneCustomer` VARCHAR(45) NULL DEFAULT NULL,
  `emailCustomer` VARCHAR(45) NULL DEFAULT NULL,
  `addressCustomer` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `warehouse`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouse`.`product` ;

CREATE TABLE IF NOT EXISTS `warehouse`.`product` (
  `idProduct` INT(11) NOT NULL,
  `nameProduct` VARCHAR(45) NOT NULL,
  `categoryId` INT(11) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `quantityOnStock` INT(11) NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_product_category_idx` (`categoryId` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`categoryId`)
    REFERENCES `warehouse`.`category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `warehouse`.`orderitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouse`.`orderitem` ;

CREATE TABLE IF NOT EXISTS `warehouse`.`orderitem` (
  `idOrderItem` INT(11) NOT NULL,
  `customerId` INT(11) NOT NULL,
  `productId` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`idOrderItem`),
  INDEX `fk_order_customer_idx` (`customerId` ASC),
  INDEX `fk_order_product_idx` (`productId` ASC),
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`customerId`)
    REFERENCES `warehouse`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product`
    FOREIGN KEY (`productId`)
    REFERENCES `warehouse`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
